// File: js/data.js

const GAME_DATA = {
  // Kategori ini bisa Anda tambah terus menerus
  categories: {
    animals: {
      displayName: "Animals",
      words: [
        { en: "Cat", id: "Kucing", image: "kucing.jpg" },
        { en: "Dog", id: "Anjing", image: "anjing.jpg" },
        { en: "Bird", id: "Burung", image: "burung.jpg" },
        { en: "Fish", id: "Ikan", image: "ikan.jpg" },
        { en: "Duck", id: "Bebek", image: "bebek.jpg" },
        { en: "Chicken", id: "Ayam", image: "ayam.jpg" },
        { en: "Horse", id: "Kuda", image: "kuda.jpg" },
        { en: "Cow", id: "Sapi", image: "sapi.jpg" },
        { en: "Goat", id: "Kambing", image: "kambing.jpg" },
        { en: "Sheep", id: "Domba", image: "domba.jpg" },
        { en: "Pig", id: "Babi", image: "babi.jpg" },
        { en: "Elephant", id: "Gajah", image: "gajah.jpg" },
        { en: "Lion", id: "Singa", image: "singa.jpg" },
        { en: "Tiger", id: "Harimau", image: "harimau.jpg" },
        { en: "Bear", id: "Beruang", image: "beruang.jpg" },
        { en: "Monkey", id: "Monyet", image: "monyet.jpg" },
        { en: "Snake", id: "Ular", image: "ular.jpg" },
        { en: "Crocodile", id: "Buaya", image: "buaya.jpg" },
        { en: "Frog", id: "Kodok", image: "kodok.jpg" },
        { en: "Turtle", id: "Kura-kura", image: "kura-kura.jpg" },
        { en: "Rabbit", id: "Kelinci", image: "kelinci.jpg" },
        { en: "Deer", id: "Rusa", image: "rusa.jpg" },
        { en: "Mouse", id: "Tikus", image: "tikus.jpg" },
        { en: "Squirrel", id: "Tupai", image: "tupai.jpg" },
        { en: "Bat", id: "Kelelawar", image: "kelelawar.jpg" },
        { en: "Whale", id: "Paus", image: "paus.jpg" },
        { en: "Dolphin", id: "Lumba-lumba", image: "lumba-lumba.jpg" },
        { en: "Shark", id: "Hiu", image: "hiu.jpg" },
        { en: "Octopus", id: "Gurita", image: "gurita.jpg" },
        { en: "Crab", id: "Kepiting", image: "kepiting.jpg" },
        { en: "Butterfly", id: "Kupu-kupu", image: "kupu-kupu.jpg" },
        { en: "Ant", id: "Semut", image: "semut.jpg" },
        { en: "Bee", id: "Lebah", image: "lebah.jpg" },
        { en: "Mosquito", id: "Nyamuk", image: "nyamuk.jpg" },
        { en: "Cockroach", id: "Kecoa", image: "kecoa.jpg" },
        { en: "Spider", id: "Laba-laba", image: "laba-laba.jpg" },
        { en: "Eagle", id: "Elang", image: "elang.jpg" },
        { en: "Owl", id: "Burung hantu", image: "burung-hantu.jpg" },
        { en: "Parrot", id: "Nuri", image: "nuri.jpg" },
        { en: "Peacock", id: "Merak", image: "merak.jpg" },
        { en: "Penguin", id: "Penguin", image: "penguin.jpg" },
        { en: "Kangaroo", id: "Kanguru", image: "kanguru.jpg" },
        { en: "Giraffe", id: "Jerapah", image: "jerapah.jpg" },
        { en: "Zebra", id: "Zebra", image: "zebra.jpg" },
        { en: "Hippopotamus", id: "Kuda nil", image: "kuda-nil.jpg" },
        { en: "Rhinoceros", id: "Badak", image: "badak.jpg" },
        { en: "Wolf", id: "Serigala", image: "serigala.jpg" },
        { en: "Fox", id: "Rubah", image: "rubah.jpg" },
        { en: "Panda", id: "Panda", image: "panda.jpg" },
        { en: "Koala", id: "Koala", image: "koala.jpg" },
        { en: "Platypus", id: "Platipus", image: "platipus.jpg" },
        { en: "Seal", id: "Anjing laut", image: "anjing-laut.jpg" },
        { en: "Walrus", id: "Walrus", image: "walrus.jpg" },
        { en: "Jellyfish", id: "Ubur-ubur", image: "ubur-ubur.jpg" },
        { en: "Starfish", id: "Bintang laut", image: "bintang-laut.jpg" },
        { en: "Seahorse", id: "Kuda laut", image: "kuda-laut.jpg" },
        { en: "Camel", id: "Unta", image: "unta.jpg" },
        { en: "Donkey", id: "Keledai", image: "keledai.jpg" },
        { en: "Buffalo", id: "Kerbau", image: "kerbau.jpg" },
        { en: "Pigeon", id: "Merpati", image: "merpati.jpg" },
        { en: "Swan", id: "Angsa", image: "angsa.jpg" },
        { en: "Flamingo", id: "Flamingo", image: "flamingo.jpg" },
        { en: "Ostrich", id: "Burung unta", image: "burung-unta.jpg" },
      ],
    },
    fruits: {
      displayName: "Fruits",
      words: [
        { en: "Apple", id: "Apel", image: "apel.jpeg" },
        { en: "Banana", id: "Pisang", image: "pisang.jpeg" },
        { en: "Orange", id: "Jeruk", image: "jeruk.jpeg" },
        { en: "Grape", id: "Anggur", image: "anggur.jpeg" },
        { en: "Strawberry", id: "Stroberi", image: "strowberi.jpeg" },
        { en: "Watermelon", id: "Semangka", image: "semangka.jpeg" },
        { en: "Pineapple", id: "Nanas", image: "nanas.jpeg" },
        { en: "Mango", id: "Mangga", image: "mangga.jpeg" },
        { en: "Papaya", id: "Pepaya", image: "pepaya.jpeg" },
        { en: "Guava", id: "Jambu biji", image: "jambu-biji.jpeg" },
        { en: "Dragon Fruit", id: "Buah naga", image: "buah-naga.jpeg" },
        { en: "Durian", id: "Durian", image: "durian.jpeg" },
        { en: "Rambutan", id: "Rambutan", image: "rambutan.jpeg" },
        { en: "Mangosteen", id: "Manggis", image: "manggis.jpeg" },
        { en: "Jackfruit", id: "Nangka", image: "nangka.jpeg" },
        { en: "Passion Fruit", id: "Markisa", image: "markisa.jpeg" },
        { en: "Soursop", id: "Sirsak", image: "sirsak.jpeg" },
        { en: "Longan", id: "Lengkeng", image: "lengkeng.jpeg" },
        { en: "Lychee", id: "Leci", image: "leci.jpeg" },
        { en: "Blueberry", id: "Bluberi", image: "bluberi.jpeg" },
        { en: "Raspberry", id: "Raspberi", image: "Raspberi.jpeg" },
        { en: "Blackberry", id: "Blackberi", image: "blackberi.jpeg" },
        { en: "Cherry", id: "Ceri", image: "ceri.jpeg" },
        { en: "Lemon", id: "Lemon", image: "lemon.jpeg" },
        { en: "Tangerine", id: "Jeruk keprok", image: "jeruk-keprok.jpeg" },
        { en: "Peach", id: "Persik", image: "persik.jpeg" },
        { en: "Plum", id: "Prem", image: "prem.jpeg" },
        { en: "Apricot", id: "Aprikot", image: "aprikot.jpeg" },
        { en: "Avocado", id: "Alpukat", image: "alpukat.jpeg" },
        { en: "Cantaloupe", id: "Melon", image: "melon.jpeg" },
        { en: "Honeydew", id: "Melon hijau", image: "melon-hijau.jpeg" },
        { en: "Rockmelon", id: "Melon jingga", image: "melon-jingga.jpeg" },
        { en: "Kiwi", id: "Kiwi", image: "kiwi.jpeg" },
        { en: "Pomegranate", id: "Delima", image: "delima.jpeg" },
        { en: "Fig", id: "Ara", image: "ara.jpeg" },
        { en: "Persimmon", id: "Kesemek", image: "kesemek.jpeg" },
        { en: "Star Fruit", id: "Belimbing", image: "belimbing.jpeg" },
        { en: "Coconut", id: "Kelapa", image: "kelapa.jpeg" },
        { en: "Date", id: "Kurma", image: "kurma.jpeg" },
        { en: "Gooseberry", id: "Gooseberi", image: "gooseberi.jpeg" },
        { en: "Cranberry", id: "Kranberi", image: "kranberi.jpeg" },
        { en: "Elderberry", id: "Elderberi", image: "elderberi.jpeg" },
      ],
    },
    objects: {
      displayName: "Objects in the house",
      words: [
        { en: "Sofa", id: "Sofa", image: "sofa.jpg" },
        { en: "Coffee table", id: "Meja kopi", image: "mejakopi.jpg" },
        { en: "Television", id: "Televisi", image: "televisi.jpg" },
        { en: "Remote control", id: "Remote", image: "remote.jpg" },
        { en: "Carpet", id: "Karpet", image: "karpet.jpg" },
        { en: "Bookshelf", id: "Rak buku", image: "Bookshelf.jpg" },
        { en: "Picture frame", id: "Bingkai foto", image: "bingkai-foto.jpg" },
        { en: "Vase", id: "Vas", image: "vas.jpg" },
        { en: "Refrigerator", id: "Kulkas", image: "kulkas.jpg" },
        { en: "Stove", id: "Kompor", image: "kompor.jpg" },
        { en: "Sink", id: "Wastafel", image: "wastafel.jpg" },
        { en: "Cabinet", id: "Lemari dapur", image: "lemaridapur.jpg" },
        { en: "Plate", id: "Piring", image: "piring.jpg" },
        { en: "Glass", id: "Gelas", image: "gelas.jpg" },
        { en: "Fork", id: "Garpu", image: "garpu.jpg" },
        { en: "Spoon", id: "Sendok", image: "sendok.jpg" },
        { en: "Knife", id: "Pisau", image: "pisau.jpg" },
        { en: "Pan", id: "Panci", image: "panci.jpg" },
        { en: "Cutting board", id: "Talenan", image: "talenan.jpg" },
        { en: "Bowl", id: "Mangkuk", image: "mangkuk.jpg" },
        { en: "Pillow", id: "Bantal", image: "bantal.jpg" },
        { en: "Blanket", id: "Selimut", image: "selimut.jpg" },
        { en: "Wardrobe", id: "Lemari pakaian", image: "Wardrobe.jpg" },
        { en: "Dresser", id: "Lemari rias", image: "lemaririas.jpg" },
        { en: "Mirror", id: "Cermin", image: "cermin.jpg" },
        { en: "Alarm clock", id: "Jam weker", image: "jamweker.jpg" },
        { en: "Hanger", id: "Gantungan baju", image: "gantunganbaju.jpg" },
        {
          en: "Laundry basket",
          id: "Keranjang cucian",
          image: "keranjang-cucian.jpg",
        },
        { en: "Toilet", id: "Toilet", image: "toilet.jpg" },
        { en: "Towel", id: "Handuk", image: "handuk.jpg" },
        { en: "Toothbrush", id: "Sikat gigi", image: "sikatgigi.jpg" },
        { en: "Toothpaste", id: "Pasta gigi", image: "pastagigi.jpg" },
        { en: "Soap", id: "Sabun", image: "sabun.jpg" },
        { en: "Shampoo", id: "Sampo", image: "sampo.jpg" },
        { en: "Comb", id: "Sisir", image: "sisir.jpg" },
        { en: "Razor", id: "Pisaucukur", image: "pisaucukur.jpg" },
        { en: "Desk", id: "Meja kerja", image: "mejakerja.jpg" },
        { en: "Computer", id: "Komputer", image: "komputer.jpg" },
        { en: "Keyboard", id: "Keyboard", image: "keyboard.jpg" },
        { en: "Mouse", id: "Mouse", image: "mouse.jpg" },
        { en: "Printer", id: "Printer", image: "printer.jpg" },
        { en: "Notebook", id: "Buku catatan", image: "bukucatatan.jpg" },
        { en: "Pen", id: "Pulpen", image: "pulpen.jpg" },
        { en: "Pencil", id: "Pensil", image: "pensil.jpg" },
        { en: "Stapler", id: "Stepler", image: "stepler.jpg" },
        { en: "Washing machine", id: "Mesincuci", image: "mesincuci.jpg" },
        { en: "Drying rack", id: "Rak jemuran", image: "rak-jemuran.jpg" },
        { en: "Iron", id: "Setrika", image: "setrika.jpg" },
        {
          en: "Ironing board",
          id: "Papan setrika",
          image: "papan-setrika.jpg",
        },
        { en: "Detergent", id: "Deterjen", image: "deterjen.jpg" },
        { en: "Broom", id: "Sapu", image: "sapu.jpg" },
        { en: "Mop", id: "Pel", image: "pel.jpg" },
        { en: "Bucket", id: "Ember", image: "ember.jpg" },
        { en: "Flashlight", id: "Senter", image: "senter.jpg" },
        { en: "Batteries", id: "Baterai", image: "baterai.jpg" },
        { en: "Key", id: "Kunci", image: "kunci.jpg" },
        { en: "Umbrella", id: "Payung", image: "payung.jpg" },
        { en: "Ladder", id: "Tangga", image: "tangga.jpg" },
      ],
    },
    transportation: {
      displayName: "Transportasi",
      words: [
        { en: "Car", id: "Mobil" },
        { en: "Motorcycle", id: "Sepeda motor" },
        { en: "Bicycle", id: "Sepeda" },
        { en: "Bus", id: "Bus" },
        { en: "Truck", id: "Truk" },
        { en: "Train", id: "Kereta api" },
        { en: "Subway", id: "Kereta bawah tanah" },
        { en: "Tram", id: "Trem" },
        { en: "Taxi", id: "Taksi" },
        { en: "Bajaj", id: "Bajaj" },
        { en: "Becak", id: "Becak" },
        { en: "Pedicab", id: "Becak dayung" },
        { en: "Horse carriage", id: "Kereta kuda" },
        { en: "Bulldozer", id: "Buldozer" }, // Alat berat
        { en: "Tractor", id: "Traktor" },

        // Kendaraan Udara
        { en: "Airplane", id: "Pesawat terbang" },
        { en: "Helicopter", id: "Helikopter" },
        { en: "Drone", id: "Drone" },
        { en: "Hot air balloon", id: "Balon udara" },
        { en: "Glider", id: "Pesawat layang" },
        { en: "Jet", id: "Pesawat jet" },

        // Kendaraan Air
        { en: "Ship", id: "Kapal" },
        { en: "Boat", id: "Perahu" },
        { en: "Speedboat", id: "Kapal cepat" },
        { en: "Ferry", id: "Kapal feri" },
        { en: "Yacht", id: "Kapal pesiar" },
        { en: "Canoe", id: "Kano" },
        { en: "Kayak", id: "Kayak" },
        { en: "Submarine", id: "Kapal selam" },
        { en: "Sailboat", id: "Perahu layar" },
        { en: "Jukung", id: "Jukung" }, // Perahu tradisional Indonesia

        // Transportasi Umum & Khusus
        { en: "Ambulance", id: "Ambulans" },
        { en: "Fire truck", id: "Mobil pemadam kebakaran" },
        { en: "Police car", id: "Mobil polisi" },
        { en: "Tow truck", id: "Mobil derek" },
        { en: "Delivery truck", id: "Truk pengantar" },
        { en: "School bus", id: "Bus sekolah" },
        { en: "RV (Recreational Vehicle)", id: "Mobil kemping" },
        { en: "Scooter", id: "Skuter" },
        { en: "Segway", id: "Segway" },
        { en: "Electric bike", id: "Sepeda listrik" },
        { en: "Monorail", id: "Monorel" },
        { en: "Cable car", id: "Kereta gantung" },
        { en: "Forklift", id: "Forklift" }, // Alat angkut
      ],
    },
    verbs: {
      displayName: "Verbs",
      words: [
        { en: "Eat", id: "Makan" },
        { en: "Drink", id: "Minum" },
        { en: "Sleep", id: "Tidur" },
        { en: "Wake up", id: "Bangun" },
        { en: "Walk", id: "Berjalan" },
        { en: "Run", id: "Lari" },
        { en: "Sit", id: "Duduk" },
        { en: "Stand", id: "Berdiri" },
        { en: "Talk", id: "Bicara" },
        { en: "Listen", id: "Mendengarkan" },

        // Aktivitas Rumah
        { en: "Cook", id: "Memasak" },
        { en: "Clean", id: "Membersihkan" },
        { en: "Wash", id: "Mencuci" },
        { en: "Sweep", id: "Menyapu" },
        { en: "Read", id: "Membaca" },
        { en: "Write", id: "Menulis" },
        { en: "Watch", id: "Menonton" },
        { en: "Study", id: "Belajar" },
        { en: "Work", id: "Bekerja" },
        { en: "Play", id: "Bermain" },

        // Gerakan Fisik
        { en: "Jump", id: "Melompat" },
        { en: "Dance", id: "Menari" },
        { en: "Swim", id: "Berenang" },
        { en: "Climb", id: "Memanjat" },
        { en: "Push", id: "Mendorong" },
        { en: "Pull", id: "Menarik" },
        { en: "Lift", id: "Mengangkat" },
        { en: "Carry", id: "Membawa" },
        { en: "Throw", id: "Melempar" },
        { en: "Catch", id: "Menangkap" },

        // Interaksi Sosial
        { en: "Meet", id: "Bertemu" },
        { en: "Greet", id: "Menyapa" },
        { en: "Help", id: "Membantu" },
        { en: "Give", id: "Memberi" },
        { en: "Take", id: "Mengambil" },
        { en: "Buy", id: "Membeli" },
        { en: "Sell", id: "Menjual" },
        { en: "Ask", id: "Bertanya" },
        { en: "Answer", id: "Menjawab" },
        { en: "Invite", id: "Mengundang" },

        // Emosi & Pikiran
        { en: "Love", id: "Mencintai" },
        { en: "Like", id: "Menyukai" },
        { en: "Hate", id: "Membenci" },
        { en: "Think", id: "Berpikir" },
        { en: "Know", id: "Mengetahui" },
        { en: "Understand", id: "Memahami" },
        { en: "Remember", id: "Mengingat" },
        { en: "Forget", id: "Melupakan" },
        { en: "Hope", id: "Berharap" },
        { en: "Wish", id: "Berharap" },

        // Tindakan Khusus
        { en: "Travel", id: "Bepergian" },
        { en: "Drive", id: "Menyetir" },
        { en: "Fly", id: "Terbang" },
        { en: "Ride", id: "Mengendarai" },
        { en: "Build", id: "Membangun" },
        { en: "Fix", id: "Memperbaiki" },
        { en: "Break", id: "Memecahkan" },
        { en: "Cut", id: "Memotong" },
        { en: "Draw", id: "Menggambar" },
        { en: "Paint", id: "Melukis" },

        // Kata Kerja Tidak Beraturan (Irregular Verbs)
        { en: "Go", id: "Pergi" },
        { en: "Come", id: "Datang" },
        { en: "See", id: "Melihat" },
        { en: "Take", id: "Mengambil" },
        { en: "Make", id: "Membuat" },
        { en: "Find", id: "Menemukan" },
        { en: "Get", id: "Mendapatkan" },
        { en: "Bring", id: "Membawa" },
        { en: "Begin", id: "Memulai" },
        { en: "Keep", id: "Menyimpan" },
        { en: "Open", id: "Membuka" },
        { en: "Close", id: "Menutup" },
        { en: "Start", id: "Memulai" },
        { en: "Stop", id: "Berhenti" },
        { en: "Turn on", id: "Menyalakan" },
        { en: "Turn off", id: "Mematikan" },
        { en: "Hold", id: "Memegang" },
        { en: "Drop", id: "Menjatuhkan" },
        { en: "Touch", id: "Menyentuh" },
        { en: "Feel", id: "Merasa" },

        // Physical Actions (Aksi Fisik)
        { en: "Bend", id: "Membungkuk" },
        { en: "Stretch", id: "Merenggangkan" },
        { en: "Lean", id: "Bersandar" },
        { en: "Roll", id: "Menggulingkan" },
        { en: "Spin", id: "Berputar" },
        { en: "Kick", id: "Menendang" },
        { en: "Punch", id: "Meninju" },
        { en: "Hug", id: "Memeluk" },
        { en: "Kiss", id: "Mencium" },
        { en: "Whisper", id: "Berbisik" },

        // Mental/Cognitive Actions (Aksi Mental)
        { en: "Decide", id: "Memutuskan" },
        { en: "Choose", id: "Memilih" },
        { en: "Plan", id: "Merencanakan" },
        { en: "Imagine", id: "Membayangkan" },
        { en: "Believe", id: "Percaya" },
        { en: "Doubt", id: "Meragukan" },
        { en: "Guess", id: "Menebak" },
        { en: "Solve", id: "Memecahkan" },
        { en: "Count", id: "Menghitung" },
        { en: "Measure", id: "Mengukur" },

        // Communication (Komunikasi)
        { en: "Explain", id: "Menjelaskan" },
        { en: "Describe", id: "Mendeskripsikan" },
        { en: "Argue", id: "Berdebat" },
        { en: "Agree", id: "Setuju" },
        { en: "Disagree", id: "Tidak setuju" },
        { en: "Promise", id: "Berjanji" },
        { en: "Lie", id: "Berbohong" },
        { en: "Confess", id: "Mengakui" },
        { en: "Complain", id: "Mengeluh" },
        { en: "Praise", id: "Memuji" },

        // Daily Activities (Aktivitas Sehari-hari)
        { en: "Brush", id: "Menyikat" },
        { en: "Comb", id: "Menyisir" },
        { en: "Shower", id: "Mandi" },
        { en: "Dress", id: "Berdandan" },
        { en: "Undress", id: "Melepas pakaian" },
        { en: "Fold", id: "Melipat" },
        { en: "Iron", id: "Menyetrika" },
        { en: "Sew", id: "Menjahit" },
        { en: "Knock", id: "Mengetuk" },
        { en: "Lock", id: "Mengunci" },

        // Work/Study Related (Terhubung Pekerjaan/Studi)
        { en: "Teach", id: "Mengajar" },
        { en: "Learn", id: "Belajar" },
        { en: "Practice", id: "Berlatih" },
        { en: "Perform", id: "Melakukan" },
        { en: "Create", id: "Menciptakan" },
        { en: "Design", id: "Mendesain" },
        { en: "Calculate", id: "Menghitung" },
        { en: "Type", id: "Mengetik" },
        { en: "Print", id: "Mencetak" },
        { en: "Edit", id: "Mengedit" },

        // Irregular Verbs (Kata Kerja Tidak Beraturan)
        { en: "Become", id: "Menjadi" },
        { en: "Begin", id: "Memulai" },
        { en: "Bite", id: "Menggigit" },
        { en: "Blow", id: "Meniup" },
        { en: "Choose", id: "Memilih" },
        { en: "Do", id: "Melakukan" },
        { en: "Dream", id: "Bermimpi" },
        { en: "Fall", id: "Jatuh" },
        { en: "Feed", id: "Memberi makan" },
        { en: "Fight", id: "Bertarung" },
        { en: "Fly", id: "Terbang" },
        { en: "Forbid", id: "Melarang" },
        { en: "Freeze", id: "Membeku" },
        { en: "Grow", id: "Tumbuh" },
        { en: "Hide", id: "Bersembunyi" },
        { en: "Know", id: "Mengetahui" },
        { en: "Lead", id: "Memimpin" },
        { en: "Ride", id: "Mengendarai" },
        { en: "Ring", id: "Membunyikan bel" },
        { en: "Rise", id: "Naik" },
        { en: "Seek", id: "Mencari" },
        { en: "Shake", id: "Menggoyangkan" },
        { en: "Sing", id: "Menyanyi" },
        { en: "Sink", id: "Tenggelam" },
        { en: "Slide", id: "Meluncur" },
        { en: "Speak", id: "Berbicara" },
        { en: "Spend", id: "Menghabiskan" },
        { en: "Spread", id: "Menyebarkan" },
        { en: "Steal", id: "Mencuri" },
        { en: "Sting", id: "Menyengat" },
        { en: "Swear", id: "Bersumpah" },
        { en: "Sweep", id: "Menyapu" },
        { en: "Swim", id: "Berenang" },
        { en: "Swing", id: "Mengayun" },
        { en: "Tear", id: "Mengoyak" },
        { en: "Throw", id: "Melempar" },
        { en: "Wake", id: "Bangun" },
        { en: "Wear", id: "Memakai" },
        { en: "Weep", id: "Menangis" },
        { en: "Win", id: "Menang" },
        { en: "Withdraw", id: "Menarik" },
        { en: "Write", id: "Menulis" },
      ],
    },
    numbers: {
      displayName: "Numbers",
      words: [
        { en: "One", id: "1" },
        { en: "Two", id: "2" },
        { en: "Three", id: "3" },
        { en: "Four", id: "4" },
        { en: "Five", id: "5" },
        { en: "Six", id: "6" },
        { en: "Seven", id: "7" },
        { en: "Eight", id: "8" },
        { en: "Nine", id: "9" },
        { en: "Ten", id: "10" },
      ],
    },
    simpleSentences: {
      displayName: "Simple Sentences",
      words: [
        { en: "I wake up early", id: "Saya bangun pagi" },
        { en: "She brushes her teeth", id: "Dia menyikat giginya" },
        { en: "He drinks coffee", id: "Dia minum kopi" },
        { en: "They eat breakfast", id: "Mereka makan sarapan" },
        { en: "We go to school", id: "Kami pergi ke sekolah" },
        { en: "You work in an office", id: "Kamu bekerja di kantor" },
        { en: "My mother cooks dinner", id: "Ibuku memasak makan malam" },
        {
          en: "The baby sleeps in the crib",
          id: "Bayi tidur di tempat tidur bayi",
        },
        { en: "Father reads the newspaper", id: "Ayah membaca koran" },
        { en: "We live in a big house", id: "Kami tinggal di rumah besar" },
        { en: "She cleans her room", id: "Dia membersihkan kamarnya" },
        { en: "They watch TV together", id: "Mereka menonton TV bersama" },
        { en: "The sun shines brightly", id: "Matahari bersinar terang" },
        { en: "It rains heavily", id: "Hujan turun deras" },
        {
          en: "Birds sing in the trees",
          id: "Burung-burung bernyanyi di pohon",
        },
        {
          en: "Flowers bloom in spring",
          id: "Bunga-bunga bermekaran di musim semi",
        },
        { en: "The wind blows strongly", id: "Angin bertiup kencang" },
        { en: "Leaves fall from trees", id: "Daun-daun jatuh dari pohon" },

        // Food & Drinks (Makanan & Minuman)
        { en: "I like chocolate ice cream", id: "Saya suka es krim cokelat" },
        { en: "She buys fresh vegetables", id: "Dia membeli sayuran segar" },
        { en: "He drinks cold water", id: "Dia minum air dingin" },
        { en: "We cook rice every day", id: "Kami memasak nasi setiap hari" },
        { en: "You cut the apple", id: "Kamu memotong apel" },
        { en: "They share the cake", id: "Mereka berbagi kue" },

        // Animals (Hewan)
        { en: "The dog barks loudly", id: "Anjing menggonggong keras" },
        { en: "Cats chase mice", id: "Kucing mengejar tikus" },
        { en: "Fish swim in the pond", id: "Ikan berenang di kolam" },
        { en: "Bees make honey", id: "Lebah membuat madu" },
        { en: "The horse runs fast", id: "Kuda berlari cepat" },
        { en: "Birds build nests", id: "Burung membuat sarang" },

        // School & Learning (Sekolah & Belajar)
        { en: "Students raise their hands", id: "Siswa mengangkat tangan" },
        {
          en: "The teacher writes on the board",
          id: "Guru menulis di papan tulis",
        },
        { en: "We study mathematics", id: "Kami belajar matematika" },
        {
          en: "She reads an English book",
          id: "Dia membaca buku bahasa Inggris",
        },
        { en: "They draw pictures", id: "Mereka menggambar gambar" },
        { en: "I answer the question", id: "Saya menjawab pertanyaan" },

        // Transportation (Transportasi)
        { en: "The bus stops here", id: "Bus berhenti di sini" },
        { en: "He rides a bicycle", id: "Dia mengendarai sepeda" },
        { en: "We wait for the train", id: "Kami menunggu kereta" },
        { en: "She drives carefully", id: "Dia menyetir dengan hati-hati" },
        { en: "The airplane flies high", id: "Pesawat terbang tinggi" },
        { en: "Boats float on water", id: "Perahu mengapung di air" },

        // Emotions & Feelings (Emosi & Perasaan)
        { en: "I feel happy today", id: "Saya merasa senang hari ini" },
        { en: "She looks sad", id: "Dia terlihat sedih" },
        { en: "They seem excited", id: "Mereka tampak bersemangat" },
        { en: "We get angry sometimes", id: "Kami marah kadang-kadang" },
        { en: "You sound worried", id: "Kamu terdengar khawatir" },
        { en: "He acts shy", id: "Dia bertingkah pemalu" },

        // Time & Numbers (Waktu & Angka)
        {
          en: "Monday comes after Sunday",
          id: "Hari Senin datang setelah Minggu",
        },
        {
          en: "December is the last month",
          id: "Desember adalah bulan terakhir",
        },
        {
          en: "Five plus five equals ten",
          id: "Lima tambah lima sama dengan sepuluh",
        },
        { en: "I wake up at seven o'clock", id: "Saya bangun jam tujuh" },
        { en: "The meeting lasts two hours", id: "Rapat berlangsung dua jam" },
        { en: "She arrives before noon", id: "Dia tiba sebelum tengah hari" },

        // Shopping (Belanja)
        { en: "We buy new clothes", id: "Kami membeli baju baru" },
        { en: "She pays with cash", id: "Dia membayar dengan tunai" },
        { en: "The store opens at nine", id: "Toko buka jam sembilan" },
        { en: "They sell fresh fruit", id: "Mereka menjual buah segar" },
        { en: "I need a shopping bag", id: "Saya perlu tas belanja" },
        { en: "You try on the shoes", id: "Kamu mencoba sepatu" },

        { en: "I wash my hands", id: "Saya mencuci tangan" },
        { en: "She combs her hair", id: "Dia menyisir rambutnya" },
        { en: "He exercises daily", id: "Dia berolahraga setiap hari" },
        { en: "We visit the doctor", id: "Kami mengunjungi dokter" },
        { en: "You take medicine", id: "Kamu minum obat" },
        { en: "They feel better now", id: "Mereka merasa lebih baik sekarang" },

        { en: "I use my phone", id: "Saya menggunakan telepon saya" },
        { en: "She sends an email", id: "Dia mengirim email" },
        { en: "He fixes the computer", id: "Dia memperbaiki komputer" },
        { en: "We watch YouTube videos", id: "Kami menonton video YouTube" },
        { en: "You charge your laptop", id: "Kamu mengisi daya laptopmu" },
        { en: "They play video games", id: "Mereka bermain video game" },
      ],
    },
    colors: {
      displayName: "Colors",
      words: [
        // Basic Colors
        { en: "Red", id: "Merah" },
        { en: "Blue", id: "Biru" },
        { en: "Green", id: "Hijau" },
        { en: "Yellow", id: "Kuning" },
        { en: "Orange", id: "Jingga" },
        { en: "Purple", id: "Ungu" },
        { en: "Black", id: "Hitam" },
        { en: "White", id: "Putih" },
        { en: "Pink", id: "Merah Muda" },
        { en: "Brown", id: "Cokelat" },
        { en: "Gray", id: "Abu-abu" },
        { en: "Gold", id: "Emas" },
        { en: "Silver", id: "Perak" },
        { en: "Turquoise", id: "Pirus" },

        // Shades & Variants (English-Indonesian)
        { en: "Dark Red", id: "Merah Tua" },
        { en: "Light Blue", id: "Biru Muda" },
        { en: "Lime Green", id: "Hijau Limau" },
        { en: "Dark Green", id: "Hijau Gelap" },
        { en: "Sky Blue", id: "Biru Langit" },
        { en: "Navy Blue", id: "Biru Dongker" },
        { en: "Beige", id: "Krem" },
        { en: "Maroon", id: "Merah Marun" },
        { en: "Violet", id: "Violet" },
        { en: "Magenta", id: "Magenta" },
        { en: "Cyan", id: "Sian" },
        { en: "Indigo", id: "Nila" },
        { en: "Olive", id: "Zaitun" },
        { en: "Teal", id: "Teal" },
        { en: "Lavender", id: "Lavender" },
        { en: "Salmon", id: "Salmon" },
        { en: "Crimson", id: "Merah Crimson" },
        { en: "Ivory", id: "Gading" },
        { en: "Charcoal", id: "Arang" },
        { en: "Ruby", id: "Ruby" },
        { en: "Amber", id: "Amber" },
        { en: "Mint Green", id: "Hijau Mint" },
        { en: "Peach", id: "Persik" },
        { en: "Rose", id: "Merah Muda (Rose)" },
        { en: "Mustard", id: "Kuning Mustar" },
        { en: "Burgundy", id: "Burgundi" },
        { en: "Coral", id: "Koral" },
        { en: "Slate Gray", id: "Abu-abu Slate" },
      ],
    },
    shapes2D: {
      displayName: "2D Shapes",
      words: [
        // Basic Shapes
        { en: "Circle", id: "Lingkaran" },
        { en: "Square", id: "Persegi" },
        { en: "Triangle", id: "Segitiga" },
        { en: "Rectangle", id: "Persegi Panjang" },
        { en: "Oval", id: "Oval" },
        { en: "Diamond", id: "Belah Ketupat" },
        { en: "Star", id: "Bintang" },
        { en: "Heart", id: "Hati" },

        // Polygons (Segi Banyak)
        { en: "Pentagon", id: "Segilima" },
        { en: "Hexagon", id: "Segienam" },
        { en: "Heptagon", id: "Segitujuh" },
        { en: "Octagon", id: "Segidelapan" },
        { en: "Nonagon", id: "Segisembilan" },
        { en: "Decagon", id: "Segi sepuluh" },

        // Quadrilaterals (Segi Empat)
        { en: "Parallelogram", id: "Jajar Genjang" },
        { en: "Trapezoid", id: "Trapesium" },
        { en: "Kite", id: "Layang-layang" },
        { en: "Rhombus", id: "Belah Ketupat" }, // Synonym for Diamond

        // Curved & Irregular Shapes
        { en: "Semicircle", id: "Setengah Lingkaran" },
        { en: "Crescent", id: "Bulan Sabit" },
        { en: "Ellipse", id: "Elips" },
        { en: "Annulus", id: "Cincin Lingkaran" },
        { en: "Sector", id: "Juring Lingkaran" },
        { en: "Segment", id: "Tembereng Lingkaran" },

        // Abstract/Symbolic Shapes
        { en: "Cross", id: "Salib" },
        { en: "Arrow", id: "Panah" },
        { en: "Cloud", id: "Awan" },
        { en: "Lightning Bolt", id: "Petir" },
      ],
    },
    shapes3D: {
      displayName: "3D Shapes",
      words: [
        // Basic 3D Shapes
        { en: "Cube", id: "Kubus" },
        { en: "Sphere", id: "Bola" },
        { en: "Cone", id: "Kerucut" },
        { en: "Cylinder", id: "Tabung" },
        { en: "Pyramid", id: "Limas" },
        { en: "Cuboid", id: "Balok" },

        // Prisms & Platonic Solids
        { en: "Triangular Prism", id: "Prisma Segitiga" },
        { en: "Pentagonal Prism", id: "Prisma Segilima" },
        { en: "Hexagonal Prism", id: "Prisma Segienam" },
        { en: "Tetrahedron", id: "Tetrahedron" },
        { en: "Octahedron", id: "Oktahedron" },
        { en: "Dodecahedron", id: "Dodekahedron" },
        { en: "Icosahedron", id: "Ikosahedron" },

        // Curved 3D Shapes
        { en: "Torus", id: "Torus (Donat)" },
        { en: "Hemisphere", id: "Setengah Bola" },
        { en: "Ellipsoid", id: "Elipsoid" },
        { en: "Paraboloid", id: "Paraboloid" },

        // Real-World 3D Forms
        { en: "Capsule", id: "Kapsul" },
        { en: "Pipe", id: "Pipa" },
        { en: "Frustum", id: "Frustum (Kerucut Terpancung)" },
      ],
    },
  },
};
